# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fbio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 659)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")


        self.verticalLayout_shift = QtWidgets.QVBoxLayout()
        self.verticalLayout_shift.setSpacing(0)
        self.verticalLayout_shift.setObjectName("verticalLayout_shift")

        self.horizontalLayout_Models = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Models.setSpacing(0)
        self.horizontalLayout_Models.setObjectName("horizontalLayout_Models")

        self.horizontalLayout_shift = QtWidgets.QHBoxLayout()
        self.horizontalLayout_shift.setSpacing(0)
        self.horizontalLayout_shift.setObjectName("horizontalLayout_shift")

        self.horizontalLayout_CheckBox = QtWidgets.QHBoxLayout()
        self.horizontalLayout_CheckBox.setSpacing(0)
        self.horizontalLayout_CheckBox.setObjectName("horizontalLayout_CheckBox")



        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.original_img_widget = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_img_widget.sizePolicy().hasHeightForWidth())
        self.original_img_widget.setSizePolicy(sizePolicy)
        self.original_img_widget.setText("")
        self.original_img_widget.setScaledContents(True)
        self.original_img_widget.setObjectName("original_img_widget")
        self.verticalLayout.addWidget(self.original_img_widget)
        self.original_title = QtWidgets.QLabel(self.centralwidget)
      #  self.original_title.setScaledContents(True)
        self.original_title.setAlignment(QtCore.Qt.AlignCenter)
        self.original_title.setObjectName("original_title")
        self.verticalLayout_shift.addWidget(self.original_title)

        self.empty3 = QtWidgets.QLabel(self.centralwidget)
        self.empty3.setScaledContents(True)
        self.empty3.setAlignment(QtCore.Qt.AlignCenter)
        self.empty3.setObjectName("empty2")
        self.verticalLayout_shift.addWidget(self.empty3)



        self.verticalLayout.setStretch(0, 90)
        self.verticalLayout.setStretch(1, 10)
      #  self.verticalLayout.addLayout(self.horizontalLayout_Models)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.output_img_widget = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_img_widget.sizePolicy().hasHeightForWidth())
        self.output_img_widget.setSizePolicy(sizePolicy)
        self.output_img_widget.setText("")
        self.output_img_widget.setScaledContents(True)
        self.output_img_widget.setObjectName("output_img_widget")
        self.verticalLayout_2.addWidget(self.output_img_widget)


   #     self.MSE = QtWidgets.QLabel(self.centralwidget)
    #    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
     #   sizePolicy.setHorizontalStretch(0)
      #  sizePolicy.setVerticalStretch(0)
       # sizePolicy.setHeightForWidth(self.MSE.sizePolicy().hasHeightForWidth())
        #self.MSE.setSizePolicy(sizePolicy)
       # self.MSE.setText("")
       # self.MSE.setScaledContents(True)
       # self.MSE.setAlignment(QtCore.Qt.AlignCenter)
       # self.MSE.setObjectName("MSE")
       # self.verticalLayout_2.addWidget(self.MSE)

        self.output_title = QtWidgets.QLabel(self.centralwidget)
        self.output_title.setScaledContents(True)
        self.output_title.setAlignment(QtCore.Qt.AlignCenter)
        self.output_title.setObjectName("output_title")
        self.verticalLayout_2.addWidget(self.output_title)
        self.verticalLayout_2.setStretch(0, 92)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_CheckBox)


        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(0, 50)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, -1, 0)
        self.gridLayout_2.setHorizontalSpacing(14)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.model_2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.model_2_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.model_2_btn.setObjectName("model_2_btn")
        # self.gridLayout_2.addWidget(self.model_2_btn, 1, 1, 1, 1)
        self.horizontalLayout_Models.addWidget(self.model_2_btn)

        self.model_3_btn_effOpt = QtWidgets.QPushButton(self.centralwidget)
        self.model_3_btn_effOpt.setMinimumSize(QtCore.QSize(0, 25))
        self.model_3_btn_effOpt.setObjectName("model_3_btn_effOpt")
        # self.gridLayout_2.addWidget(self.model_3_btn_effOpt, 1, -1, 1, 1)
        self.horizontalLayout_Models.addWidget(self.model_3_btn_effOpt)



        self.empty = QtWidgets.QLabel(self.centralwidget)
        self.empty.setScaledContents(True)
        self.empty.setAlignment(QtCore.Qt.AlignCenter)
        self.empty.setObjectName("empty")
        self.horizontalLayout_CheckBox.addWidget(self.empty)

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setAutoRepeat(False)
        self.checkBox.setAutoExclusive(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        # self.gridLayout_2.addWidget(self.checkBox, 1, 5, 1, 1)
        self.horizontalLayout_CheckBox.addWidget(self.checkBox)
        self.horizontalLayout_CheckBox.setStretch(0, 45)
        self.horizontalLayout_CheckBox.setStretch(1, 55)
        # self.checkBox.setAlignment(QtCore.Qt.AlignCenter)


        self.model_1_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_1_btn.sizePolicy().hasHeightForWidth())
        self.model_1_btn.setSizePolicy(sizePolicy)
        self.model_1_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.model_1_btn.setObjectName("model_1_btn")

        self.empty2 = QtWidgets.QLabel(self.centralwidget)
        self.empty2.setScaledContents(True)
        self.empty2.setAlignment(QtCore.Qt.AlignCenter)
        self.empty2.setObjectName("empty2")
        self.horizontalLayout_shift.addWidget(self.empty2)


        # self.gridLayout_2.addWidget(self.model_1_btn, 1, 2, 1, 1)
        self.horizontalLayout_Models.addWidget(self.model_1_btn)
        self.verticalLayout_shift.addLayout(self.horizontalLayout_Models)
      #  horizontalLayout_Models
     #   self.verticalLayout_shift.addLayout(self.horizontalLayout_Models)
        self.horizontalLayout_shift.addLayout(self.verticalLayout_shift)

        self.horizontalLayout_shift.setStretch(0, 15)
        self.horizontalLayout_shift.setStretch(1, 85)
        self.verticalLayout_shift.setStretch(0, 50)
        self.verticalLayout_shift.setStretch(1, 50)
        self.verticalLayout_shift.setStretch(2, 0)


        self.verticalLayout.addLayout(self.horizontalLayout_shift)
        self.rightSpacer = QtWidgets.QFrame(self.centralwidget)
        self.rightSpacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightSpacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightSpacer.setObjectName("rightSpacer")
        self.gridLayout_2.addWidget(self.rightSpacer, 1, 4, 1, 1)
        self.leftSpacer = QtWidgets.QFrame(self.centralwidget)
        self.leftSpacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftSpacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftSpacer.setObjectName("leftSpacer")
        self.gridLayout_2.addWidget(self.leftSpacer, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 18))
        self.menubar.setObjectName("menubar")
        self.menuUpload = QtWidgets.QMenu(self.menubar)
        self.menuUpload.setObjectName("menuUpload")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpload = QtWidgets.QAction(MainWindow)
        self.actionUpload.setObjectName("actionUpload")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuUpload.addSeparator()
        self.menuUpload.addAction(self.actionUpload)
        self.menuUpload.addAction(self.actionSave)
        self.menubar.addAction(self.menuUpload.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cephalometric Analyzer"))
        MainWindow.setWindowIcon(QtGui.QIcon('Program_Icon_3.png'))
        self.original_title.setText(_translate("MainWindow", "Original Image"))
        # self.MSE.setText(_translate("MainWindow", "  MSE = "))
        self.output_title.setText(_translate("MainWindow", "Output Image"))
        self.model_2_btn.setText(_translate("MainWindow", "DenseNet Model"))
        self.model_3_btn_effOpt.setText(_translate("MainWindow", "EffNet_2F Model"))
        self.checkBox.setText(_translate("MainWindow", "Show True landmarks"))
        self.model_1_btn.setText(_translate("MainWindow", "EffNet_3F Model"))
        self.menuUpload.setTitle(_translate("MainWindow", "File"))
        self.actionUpload.setText(_translate("MainWindow", "Upload"))
        self.actionSave.setText(_translate("MainWindow", "Save"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())